version: '3.4'

services:
  123vendasapplication:
    image: ${DOCKER_REGISTRY-}123vendasapplication
    build:
      context: .
      dockerfile: 123VendasApplication/Dockerfile
    ports:
        - "44347:44347"
    environment:
        DB_CONNECTION: "Server=mssql-server;Database=vendas;User Id=SA;Password=SuperPassword@123;"
        DbServer: "mssql-server"
        DbPort: "1433"
        DbUser: "SA"
        Password: "SuperPassword@123"
        Database: "vendas"

  mssql-server: 
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
        - "1433:1433"
    environment:
        SA_PASSWORD: "SuperPassword@123"
        ACCEPT_EULA: "Y"
    volumes:
        - C:\dados\volumes\sqlserver:/var/opt/mssql/data   
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest 
